#!/usr/bin/env sh

set -e

case $1 in
  --push)
    find . -type f -name 'dotfile-*' \
      -exec sh -c 'dot={}; cp -ruv $dot ~/.${dot#./dotfile-}' \;
  ;;
  --pull)
    cp -ruv "$2" "dotfile-${2#*.}"
  ;;
esac
